### PR TITLE
Fix: Add sharing action to folder navigation bar menu

### LINKED ISSUE #1469: [BUG] Sharing action missing from folder navigation bar menu
### Steps to reproduce
1. Navigate to any folder in the file list
2. Tap on the three-dots menu button (•••) in the top-right corner of a folder list item 
3. Observe that "Sharing" appears as the first option in the action menu
4. Navigate into that same folder
5. Tap on the three-dots menu button (•••) in the navigation bar
6. Observe that "Sharing" is missing from this action menu

### Expected behavior
The "Sharing" action should be available in both locations:
- In the action menu when tapping the three-dots button on a folder item in the list
- In the action menu when tapping the three-dots button in the navigation bar when inside that folder

This would provide consistent access to sharing functionality regardless of where the user accesses the folder actions from.

### Actual behavior
The "Sharing" action is only available in the folder list item's action menu (`.moreItem` location) but missing from the navigation bar's action menu when inside the folder (`.moreFolder` location).

### Analysis
The `CollaborateAction` class is not registered for the `.moreFolder` location. It only includes:
- `.keyboardShortcut`
- `.contextMenuSharingItem`  
- `.moreItem`
- `.moreDetailItem`
- `.accessibilityCustomAction`

But not `.moreFolder`, which is used for the navigation bar's more button when viewing folder contents.

### Client
**iOS version:** 18.5

**ownCloud app version:** 12.5.0

**Device model:** iPhone

### Server configuration
Reproducible with both:
- ownCloud 10 (classic WebDAV)
- ownCloud Infinite Scale (with Spaces)

### Proposed solution
Add `.moreFolder` to the supported locations in `CollaborateAction.swift`:

```swift
override class var locations : [OCExtensionLocationIdentifier]? { 
    return [.keyboardShortcut, .contextMenuSharingItem, .moreItem, .moreFolder, .moreDetailItem, .accessibilityCustomAction] 
}
```

Additional consideration: For root folders, sharing behavior should be consistent with server permissions and drive types (e.g., personal spaces vs project spaces).

### PR DESCRIPTION
**Pull request by michaelstingl**
## Description
This PR adds the "Sharing" action to the folder navigation bar's more menu (•••) to ensure consistency with the action menu shown for folder items in the file list.

## Related Issue
Fixes #1469

## Motivation and Context
Users expect the same actions to be available whether they access a folder's actions from:
- The three-dots menu on a folder item in the file list
- The three-dots menu in the navigation bar when inside that folder

Previously, the "Sharing" action was only available in the file list context menu but missing from the navigation bar menu.

## How Has This Been Tested?
- Tested on iPhone with iOS 18.5
- Verified with both ownCloud 10 and ownCloud Infinite Scale servers
- Confirmed that:
  - Sharing appears in regular folder navigation bar menus
  - Sharing is correctly hidden for OC10 root folders
  - Sharing is correctly hidden for oCIS virtual and personal space roots
  - Sharing is available for oCIS project space roots (when allowed by server)

## Screenshots (if appropriate):
N/A - UI remains the same, just adds the missing menu item

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by michaelstingl** [comment]
Added a simple unit test in the second commit to verify the location is included. Happy to adjust or remove if you prefer a different approach!

**Comment by jesmrec** [comment]
Thanks Michael for your contribution!! let's take a look into there ;)

File: ownCloud/Client/Actions/Actions+Extensions/CollaborateAction.swift [hunk 1]
```diff
@@ -24,13 +24,29 @@ class CollaborateAction: Action {
...
 	override class var name : String { return OCLocalizedString("Sharing", nil) }
-	override class var locations : [OCExtensionLocationIdentifier]? { return [.keyboardShortcut, .contextMenuSharingItem, .moreItem, .moreDetailItem, .accessibilityCustomAction] }
+	override class var locations : [OCExtensionLocationIdentifier]? { return [.keyboardShortcut, .contextMenuSharingItem, .moreItem, .moreFolder, .moreDetailItem, .accessibilityCustomAction] }
 	override class var keyCommand : String? { return "S" }
 	override class var keyModifierFlags: UIKeyModifierFlags? { return [.command] }
 
 	// MARK: - Extension matching
 	override class func applicablePosition(forContext: ActionContext) -> ActionPosition {
 		if forContext.items.count == 1, let core = forContext.core, core.connectionStatus == .online, core.connection.capabilities?.sharingAPIEnabled == 1, let item = forContext.items.first, item.isShareable {
+			// For .moreFolder location: Check special cases at root level
```
Comment (felix-schwarz) [inline ownCloud/Client/Actions/Actions+Extensions/CollaborateAction.swift:34]: The checks carried out here should not be necessary as the cases it tries to handle should already be prevented by checking `item.isShareable`, which relies on the permissions returned by the server.

The action should also not show up for root folders even without that code. Can you verify/reproduce?

File: ownCloudTests/Actions/CollaborateActionTests.swift [hunk 2]
```diff
@@ -0,0 +1,51 @@
+//
```
Comment (felix-schwarz) [inline ownCloudTests/Actions/CollaborateActionTests.swift:1]: Thanks for the effort, but I think a unit test for such a small change is not necessary.

File: ownCloud/Client/Actions/Actions+Extensions/CollaborateAction.swift [hunk 3]
```diff
@@ -24,13 +24,29 @@ class CollaborateAction: Action {
 	override class var identifier : OCExtensionIdentifier? { return OCExtensionIdentifier("com.owncloud.action.collaborate") }
 	override class var category : ActionCategory? { return .normal }
 	override class var name : String { return OCLocalizedString("Sharing", nil) }
-	override class var locations : [OCExtensionLocationIdentifier]? { return [.keyboardShortcut, .contextMenuSharingItem, .moreItem, .moreDetailItem, .accessibilityCustomAction] }
+	override class var locations : [OCExtensionLocationIdentifier]? { return [.keyboardShortcut, .contextMenuSharingItem, .moreItem, .moreFolder, .moreDetailItem, .accessibilityCustomAction] }
```
Comment (felix-schwarz) [inline ownCloud/Client/Actions/Actions+Extensions/CollaborateAction.swift:27]: I think the change in this line should be the only change necessary to implement the change. The rest should not be needed.

**Comment by jesmrec** [comment]
That's a good catch ;)

Fixed and approved from my side.

**Review by jesmrec — APPROVED** [review]

**Comment by jesmrec** [comment]
Done!
